Vagrant.configure(2) do |config|
	puts "It begins!"
	config.vm.hostname = "DANBOX.qac.local"
	config.vm.box = "chad-thompson/ubuntu-trusty64-gui"
	config.vm.box_check_update = false
	config.vm.network "private_network", ip: "192.168.33.224"
	config.vm.synced_folder "C:/Users/Administrator/Documents/VagrantSet", "/vagrant_data"
	config.vm.provider "virtualbox" do |vb|
		vb.name = "thebestbox"
		vb.cpus = 2
		vb.gui = true
		vb.memory = "8080"
	end
	puts "It Starts!"
	config.vm.provision "shell", path:"bootstrap.sh"
	config.vm.provision "shell", path:"bootstrap.sh"
end
